apiVersion: apps/v1
kind: Deployment
metadata:
  name: yoga-studio-app-deployment
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-security-groups: "sg-061d0cec3ed96cd48"
  labels:
    app: yoga-studio-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yoga-studio-app
  template:
    metadata:
      labels:
        app: yoga-studio-app
    spec:
      automountServiceAccountToken: false
      limits:
      - type: PersistentVolumeClaim
        max:
          storage: 2Gi
        min:
          storage: 1Gi
      containers:
      - name: yoga-studio-app-container
        image: DOCKER_IMAGE
        ports:
        - containerPort: 3000
        env:
        - name: EXAMPLE_ENV_VAR
          value: "example-value"
        resources:
          requests:
            memory: "128Mi"
          limits:
            memory: "256Mi"



