apiVersion: v1
kind: Service
metadata:
  name: yoga-studio-app-service
  labels:
    app: yoga-studio-app
spec:
  selector:
    app: yoga-studio-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
